### PR TITLE
Add structs and enums for ID3D12Heap

### PR DESCRIPTION
**Pull request by DethRaid**
I've added the structs and enums needed to create an `ID3D12Heap`. I've also added the method `create_heap` to `Device`, and and added the module imports and reexports to the appropriate places

The weird thing here is `heap::Flags`. Thing is, D3D12 uses the value 0 for two of the enum constants in `D3D12_HEAP_FLAGS`. Rust does not allow the same value to be used by multiple enum constants (that I know of). I made an enum without any useful values, then gave it constants with the values from `D3D12_HEAP_FLAGS`. This lets my code compile, and the syntax to use the enum is the same, but the compiler complains about capitalization and I don't really like it. I'd welcome any ideas about a better way to implement this

### CODE REVIEW

**Comment by 64** [comment]
For things that aren’t mutually exclusive it’s better to use `bitflags!`, e.g https://github.com/gfx-rs/d3d12-rs/blob/master/src/descriptor.rs#L159

**Comment by DethRaid** [comment]
I could, but it'll have to wait until I'm home from work in like eight hours

GitHub should have a way to squash and merge a PR. I think you have to enable it in the repo settings but it works pretty well

Otherwise yeah I'll get this squashed as soon as I get home

**Comment by kvark** [comment]
@DethRaid we can't squash for you if we merge using Bors, and that has been our workflow in gfx-rs for years.

**Comment by DethRaid** [comment]
Oh sorry, I didn't know

My commits should be nicely squashed now

**Comment by kvark** [comment]
No problemo, and thank you!
Bors r=msiglreith

**Pull request merged**
